services:
  ccminer:
    build:
      context: .
      dockerfile: Dockerfile-ccminer
    command: /root/ccminer/ccminer -a sha256d -o stratum+tcp://sha256.usa-west.nicehash.com:3334 -u 35wXssceVET45koSKXA93g6YKdfiMEzyDY
    # restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ['0', '3']
              capabilities: [gpu]
