FROM nvidia/cuda:11.4.1-devel-ubuntu20.04

RUN apt update
RUN apt install -y libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential git
RUN cd ~/ && git clone https://github.com/tpruvot/ccminer.git -b linux
RUN cd ~/ccminer && ./autogen.sh && ./configure --with-cuda=/usr/local/cuda && make -j$(($(nproc)+1)) && make install
